on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, reopened]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install deps
              run: bun install

            - name: Run Test
              run: bun test
